return {
	coruwafus = {
		name = "Advanced Underwater Fusion Reactor",
		description = "Produces 3000 Energy (Hazardous)",
		activatewhenbuilt = true,
		buildangle = 8192,
		buildpic = "CORUWAFUS.DDS",
		buildtime = 329200,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "84 95 84",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 48000,
		energymake = 3000,
		energystorage = 9000,
		explodeas = "fusionExplosion-uw",
		footprintx = 6,
		footprintz = 6,
		health = 9800,
		hidedamage = true,
		maxacc = 0,
		maxdec = 0,
		maxslope = 16,
		metalcost = 9700,
		minwaterdepth = 25,
		objectname = "Units/coruwafus.s3o",
		script = "Units/CORAFUS.cob",
		seismicsignature = 0,
		selfdestructas = "fusionExplosionSelfd-uw",
		sightdistance = 273,
		yardmap = "oooooooooooooooooooooooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 9,
			buildinggrounddecalsizey = 9,
			buildinggrounddecaltype = "decals/coruwfus_aoplane.dds",
			model_author = "RandomGuy",
			normaltex = "unittextures/cor_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "CorBuildings/SeaEconomy",
			techlevel = 2,
			unitgroup = "energy",
			restrictions_inclusion = "_nofusion_",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-5.1672668457 -0.194635522461 -0.799919128418",
				collisionvolumescales = "114.264892578 89.6709289551 97.8311309814",
				collisionvolumetype = "Box",
				damage = 17100,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 4,
				height = 20,
				metal = 6440,
				object = "Units/corafus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 8550,
				footprintx = 5,
				footprintz = 4,
				height = 4,
				metal = 2576,
				object = "Units/cor4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6", [2] = "count5", [3] = "count4",
				[4] = "count3", [5] = "count2", [6] = "count1",
			},
			select = {
				[1] = "watfusn2",
			},
		},
	},
}
