return {
	armuwafus = {
		name = "Advanced Underwater Fusion Reactor",
		description = "Produces 3000 Energy (Hazardous)",
		activatewhenbuilt = true,
		buildangle = 8192,
		buildpic = "ARMUWAFUS.DDS",
		buildtime = 312500,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "96 96 96",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 69000,
		energymake = 3000,
		energystorage = 9000,
		explodeas = "fusionExplosion-uw",
		footprintx = 6,
		footprintz = 6,
		health = 8300,
		hidedamage = true,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		metalcost = 9700,
		minwaterdepth = 25,
		objectname = "Units/armuwafus.s3o",
		script = "Units/ARMAFUS.cob",
		seismicsignature = 0,
		selfdestructas = "fusionExplosionSelfd-uw",
		sightdistance = 273,
		yardmap = "oooooooooooooooooooooooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 9,
			buildinggrounddecalsizey = 9,
			buildinggrounddecaltype = "decals/armuwfus_aoplane.dds",
			model_author = "RandomGuy",
			normaltex = "unittextures/Arm_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "ArmBuildings/SeaEconomy",
			techlevel = 2,
			unitgroup = "energy",
			restrictions_inclusion = "_nofusion_",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "96 96 96",
				collisionvolumetype = "Box",
				damage = 16290,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 4,
				height = 40,
				metal = 6441,
				object = "Units/armafus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "96.0 14.0 6.0",
				collisionvolumetype = "box",
				damage = 8145,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 2576,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6", [2] = "count5", [3] = "count4",
				[4] = "count3", [5] = "count2", [6] = "count1",
			},
			select = {
				[1] = "watfusn1",
			},
		},
	},
}
