return {
	leguwafus = {
		name = "Advanced Underwater Fusion Reactor",
		description = "Produces 3300 Energy (Hazardous)",
		activatewhenbuilt = true,
		buildangle = 8192,
		buildpic = "LEGUWAFUS.DDS",
		buildtime = 340000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "111 103 110",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 69000,
		energymake = 3300,
		energystorage = 9000,
		explodeas = "fusionExplosion-uw",
		footprintx = 6,
		footprintz = 6,
		health = 9800,
		hidedamage = true,
		maxacc = 0,
		maxdec = 0,
		maxslope = 16,
		metalcost = 10500,
		minwaterdepth = 25,
		objectname = "Units/leguwafus.s3o",
		script = "Units/LEGAFUS.cob",
		seismicsignature = 0,
		selfdestructas = "fusionExplosionSelfd-uw",
		sightdistance = 273,
		yardmap = "oooooooooooooooooooooooooooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 10,
			buildinggrounddecalsizey = 10,
			buildinggrounddecaltype = "decals/leganavalfusion_aoplane.dds",
			model_author = "RandomGuy",
			normaltex = "unittextures/leg_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "Legion/SeaEconomy/T2",
			techlevel = 2,
			unitgroup = "energy",
			restrictions_inclusion = "_nofusion_",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "111 103 110",
				collisionvolumetype = "Box",
				damage = 16290,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 40,
				metal = 6441,
				object = "Units/legafus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "96.0 14.0 6.0",
				collisionvolumetype = "box",
				damage = 8145,
				footprintx = 6,
				footprintz = 6,
				height = 4,
				metal = 2576,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6", [2] = "count5", [3] = "count4",
				[4] = "count3", [5] = "count2", [6] = "count1",
			},
			select = {
				[1] = "watfusn2",
			},
		},
	},
}
