return {
	legbastiont3 = {
		name = "Epic Bastion",
		description = "Epic ring-beam fortress with twin heavy gauss cannons",
		activatewhenbuilt = true,
		maxacc = 0,
		maxdec = 0,
		buildangle = 4096,
		energycost = 210000,
		metalcost = 12800,
		buildpic = "legbastion.DDS",
		buildtime = 225000,
		canrepeat = false,
		category = "ALL NOTMOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "132 236 132",
		collisionvolumetype = "CylY",
		usepiececollisionvolumes = 1,
		corpse = "DEAD",
		damagemodifier = 0.20,
		energystorage = 2500,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 7,
		footprintz = 7,
		losemitheight = 112,
		health = 28500,
		maxslope = 10,
		maxwaterdepth = 0,
		nochasecategory = "VTOL",
		objectname = "Units/legbastiont3.s3o",
		onoffable = true,
		radardistance = 1500,
		radaremitheight = 112,
		script = "Units/legbastiont3.lua",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 900,
		yardmap = "yoooooy ooooooo ooooooo ooooooo ooooooo ooooooo yoooooy",
		customparams = {
			maxrange = 1375,
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/legbastion_aoplane.dds",
			buildinggrounddecalsizey = 13,
			buildinggrounddecalsizex = 13,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = "weapon",
			model_author = "Gabs, ZephyrSkies; Epic Bastion revamp by RandomGuy",
			normaltex = "unittextures/leg_normal.dds",
			reaimtime = 5,
			removewait = true,
			subfolder = "Scavengers/Buildings/DefenseOffense",
			techlevel = 3,
			epic_model_revision = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "143 211 136",
				collisionvolumetype = "CylY",
				damage = 14000,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 28,
				metal = 7800,
				object = "Units/legbastiont3_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "82 6 82",
				collisionvolumetype = "cylY",
				damage = 7000,
				footprintx = 5,
				footprintz = 5,
				height = 6,
				metal = 4200,
				object = "Units/cor3X3E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = { [1] = "cantdo4" },
			count = {
				[1] = "count6", [2] = "count5", [3] = "count4",
				[4] = "count3", [5] = "count2", [6] = "count1",
			},
			ok = { [1] = "doom" },
			select = { [1] = "doom" },
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-large-impulse",
			},
		},
		weapondefs = {
			epicheatray = {
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = true,
				beamtime = 0.12,
				camerashake = 0.25,
				corethickness = 0.55,
				craterareaofeffect = 150,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.45,
				energypershot = 1600,
				explosiongenerator = "custom:heatray-huge",
				firestarter = 95,
				firetolerance = 300,
				impulsefactor = 0,
				laserflaresize = 10,
				name = "Epic Sustained Sweepfire Heat Ray",
				noselfdamage = true,
				predictboost = 0.3,
				proximitypriority = 1,
				range = 1350,
				reloadtime = 4,
				rgbcolor = "1 0.48 0.04",
				rgbcolor2 = "1.0 0.95 0.45",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundtrigger = 1,
				thickness = 11,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1800,
				customparams = {
					sweepfire_firetime = 3.2,
					sweepfire_reloadtime = 4.0,
				},
				damage = {
					default = 360,
					vtol = 32,
				},
			},
			gausscannon = {
				areaofeffect = 32,
				avoidfeature = false,
				burnblow = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				impulsefactor = 0.123,
				name = "Epic Side Gauss Cannon",
				noselfdamage = true,
				range = 650,
				reloadtime = 2.4,
				separation = 1.8,
				nogap = false,
				sizedecay = 0.06,
				stages = 14,
				alphadecay = 0.08,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "cannhvy1",
				targetmoveerror = 0.2,
				tolerance = 8000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				customparams = {
					weapons_role = "secondary",
				},
				damage = {
					default = 300,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "epicheatray",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "gausscannon",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
			},
			[3] = {
				badtargetcategory = "VTOL",
				def = "gausscannon",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
			},
		},
	},
}
