return {
	["epic-bastion-haze-passive"] = {
		haze = {
			class = [[CHeatCloudProjectile]],
			count = 1,
			air = true,
			ground = true,
			water = true,
			underwater = false,
			properties = {
				alwaysVisible = 0,
				texture = [[explo]],
				heat = 4,
				maxheat = 5,
				heatFalloff = 1.6,
				size = 7,
				sizeGrowth = 1.7,
				pos = [[0, 0, 0]],
				speed = [[0, 0.08, 0]],
				drawOrder = 0,
			},
		},
	},
	["epic-bastion-haze-fire"] = {
		haze = {
			class = [[CHeatCloudProjectile]],
			count = 2,
			air = true,
			ground = true,
			water = true,
			underwater = false,
			properties = {
				alwaysVisible = 1,
				texture = [[explo]],
				heat = 12,
				maxheat = 16,
				heatFalloff = 2.2,
				size = 13,
				sizeGrowth = 3.4,
				pos = [[-1 r2, -1 r2, -1 r2]],
				speed = [[0, 0.14, 0]],
				drawOrder = 0,
			},
		},
	},,
	["epic-bastion-core-pulse"] = {
		pulse = {
			class = [[CSimpleParticleSystem]],
			count = 1,
			air = true,
			ground = true,
			water = true,
			underwater = false,
			properties = {
				airdrag = 0.96,
				colormap = [[1 0.35 0.02 0.11   1 0.72 0.12 0.18   1 0.92 0.45 0.08   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 0,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.04, 0]],
				numparticles = 3,
				particlelife = 14,
				particlelifespread = 4,
				particlesize = 7,
				particlesizespread = 3,
				particlespeed = 0.18,
				particlespeedspread = 0.08,
				pos = [[0, 0, 0]],
				sizemod = 0.97,
				texture = [[flare]],
			},
		},
	},
}
