name: Publish Rapid

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  rapid:
    runs-on: ubuntu-latest

    steps:
      - name: Publish randomguy-hosting:test
        uses: beyond-all-reason/rapid-hosting/action@b4a7a7ea2deb83ed89b02d4cb2e531311e0f4b00
        with:
          url: https://randomguyrapid.duckdns.org/build
          repo: randomguy-hosting
          branch: test
